### ISSUE TITLE
Wont compile through arduino IDE

### ISSUE THREAD

**Issue by JanBosNL** [bertrik/stofananas#3]
When I try and compile through the arduino IDE I get the following error.

The following code is highlighted in the stofananas.ino
`httpClient.setFollowRedirects(true);`

The resulting error message is:

> exit status 1
> 'class HTTPClient' has no member named 'setFollowRedirects'

Any idear what might be causing this? I am hoping to be able to experiment with your code to get some 4 wire APA102 leds working on some different nodeMCU pins. I have a luftdaten sensor connected and would love to have a lamp showing the air quality.

I could of course try the easy way and buy a Wemos D1 mini board and a LED shield based on the WS2812B 3 wire leds, but I have apa102 and a nodeMCU lying around anw would prefer to go that way.

**Comment by bertrik** [comment]
Updated the build instructions and verified it builds.
